import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import * as bcrypt from "bcryptjs";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

/** Curated Unsplash product photography (stable image IDs). */
const img = (id: string, w = 800) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

type SeedProduct = {
  name: string;
  vendorId: string;
  vendorName: string;
  categoryName: string;
  brand: string;
  price: number;
  stock: number;
  rating: number;
  reviewsCount: number;
  image: string;
  images?: string[];
  description: string;
};

async function main() {
  console.log("Seeding Vendex marketplace catalog...\n");

  const hash = await bcrypt.hash("password", 10);

  // ── Users / vendors ────────────────────────────────────
  const users = [
    {
      email: "buyer@vendex.com",
      passwordHash: hash,
      name: "Alexander Great",
      role: "BUYER" as const,
    },
    {
      email: "vendor@vendex.com",
      passwordHash: hash,
      name: "Urban Goods Co.",
      role: "VENDOR" as const,
      vendorId: "v_nexus",
      status: "APPROVED" as const,
      storeName: "Nexus Tech",
      storeCategory: "Bespoke Tech",
      storeDescription: "Precision electronics and everyday tools.",
    },
    {
      email: "admin@vendex.com",
      passwordHash: hash,
      name: "Platform Administrator",
      role: "ADMIN" as const,
    },
    {
      email: "vogue@vendex.com",
      passwordHash: hash,
      name: "Vogue Minimal",
      role: "VENDOR" as const,
      vendorId: "v_vogue",
      status: "APPROVED" as const,
      storeName: "Vogue Minimal",
      storeCategory: "Luxury Goods",
      storeDescription: "Refined leather goods and quiet luxury staples.",
    },
    {
      email: "aurum@vendex.com",
      passwordHash: hash,
      name: "Aurum Collective",
      role: "VENDOR" as const,
      vendorId: "v_aurum",
      status: "APPROVED" as const,
      storeName: "Aurum Collective",
      storeCategory: "Wellness & Ritual",
      storeDescription: "Movement gear for daily rituals.",
    },
    {
      email: "elementa@vendex.com",
      passwordHash: hash,
      name: "Elementa Studio",
      role: "VENDOR" as const,
      vendorId: "v_elementa",
      status: "APPROVED" as const,
      storeName: "Elementa",
      storeCategory: "Home Studio",
      storeDescription: "Objects for focused work and calm homes.",
    },
    {
      email: "atelier@vendex.com",
      passwordHash: hash,
      name: "Atelier Nord",
      role: "VENDOR" as const,
      vendorId: "v_atelier",
      status: "APPROVED" as const,
      storeName: "Atelier Nord",
      storeCategory: "Fashion",
      storeDescription: "Nordic silhouettes and seasonal layers.",
    },
    {
      email: "kitchen@vendex.com",
      passwordHash: hash,
      name: "Hearth & Copper",
      role: "VENDOR" as const,
      vendorId: "v_hearth",
      status: "APPROVED" as const,
      storeName: "Hearth & Copper",
      storeCategory: "Kitchen",
      storeDescription: "Cookware and tools for serious home cooks.",
    },
  ];

  for (const u of users) {
    const existing = await prisma.user.findUnique({ where: { email: u.email } });
    if (!existing) {
      await prisma.user.create({ data: u });
      console.log(`  User: ${u.email}`);
    } else {
      console.log(`  Skip user: ${u.email}`);
    }
  }

  // ── Categories ─────────────────────────────────────────
  const cats = [
    { name: "Bespoke Tech", slug: "bespoke-tech", description: "Wearables, audio, and deskside gear" },
    { name: "Luxury Goods", slug: "luxury-goods", description: "Leather, jewelry, and refined accessories" },
    { name: "Wellness & Ritual", slug: "wellness-ritual", description: "Fitness, recovery, and daily care" },
    { name: "Home Studio", slug: "home-studio", description: "Lighting, desks, and creative tools" },
    { name: "Fashion", slug: "fashion", description: "Apparel and seasonal layers" },
    { name: "Kitchen", slug: "kitchen", description: "Cookware, tableware, and pantry tools" },
    { name: "Outdoor", slug: "outdoor", description: "Travel and trail essentials" },
    { name: "Beauty", slug: "beauty", description: "Skin, scent, and grooming" },
  ];

  const catMap: Record<string, string> = {};
  for (const c of cats) {
    const ex = await prisma.category.findUnique({ where: { slug: c.slug } });
    if (!ex) {
      const r = await prisma.category.create({ data: c });
      catMap[c.name] = r.id;
      console.log(`  Category: ${c.name}`);
    } else {
      catMap[c.name] = ex.id;
      console.log(`  Skip category: ${c.name}`);
    }
  }

  // ── Products (rich catalog) ────────────────────────────
  const prods: SeedProduct[] = [
    // Bespoke Tech — Nexus
    {
      name: "Horizon Smartwatch Gen 4",
      vendorId: "v_nexus",
      vendorName: "Nexus Tech",
      categoryName: "Bespoke Tech",
      brand: "Nexus",
      price: 299,
      stock: 25,
      rating: 4.8,
      reviewsCount: 128,
      image: img("photo-1523275335684-37898b6baf30"),
      images: [img("photo-1523275335684-37898b6baf30"), img("photo-1434494878577-86c23bcb06b9")],
      description:
        "Titanium-finish smartwatch with multi-day battery, precision heart metrics, and sapphire glass.",
    },
    {
      name: "Studio Pro ANC Wireless",
      vendorId: "v_nexus",
      vendorName: "Nexus Tech",
      categoryName: "Bespoke Tech",
      brand: "Nexus",
      price: 449,
      stock: 12,
      rating: 5.0,
      reviewsCount: 245,
      image: img("photo-1505740420928-5e560c06d30e"),
      images: [img("photo-1505740420928-5e560c06d30e"), img("photo-1484704849700-f032a568e944")],
      description:
        "Reference-grade noise cancelling headphones with spatial audio and 40-hour endurance.",
    },
    {
      name: "Mechanical Keycap Set",
      vendorId: "v_elementa",
      vendorName: "Elementa",
      categoryName: "Bespoke Tech",
      brand: "Elementa",
      price: 65,
      stock: 30,
      rating: 4.7,
      reviewsCount: 189,
      image: img("photo-1587829741301-dc798b83add3"),
      description: "Double-shot PBT keycaps in muted graphite — profiled for MX switches.",
    },
    {
      name: "Hybrid Controller Pro",
      vendorId: "v_nexus",
      vendorName: "Nexus Tech",
      categoryName: "Bespoke Tech",
      brand: "Nexus",
      price: 129.99,
      stock: 15,
      rating: 4.5,
      reviewsCount: 124,
      image: img("photo-1606144042614-b2417e99c4e3"),
      description: "Hall-effect sticks, modular rear paddles, and low-latency wireless dongle.",
    },
    {
      name: "Arc Wireless Earbuds",
      vendorId: "v_nexus",
      vendorName: "Nexus Tech",
      categoryName: "Bespoke Tech",
      brand: "Nexus",
      price: 179,
      stock: 40,
      rating: 4.6,
      reviewsCount: 310,
      image: img("photo-1590658268037-6bf12165a8df"),
      description: "Compact buds with adaptive EQ and IPX5 weather seal.",
    },
    {
      name: "Carbon Fiber Laptop Sleeve 14\"",
      vendorId: "v_nexus",
      vendorName: "Nexus Tech",
      categoryName: "Bespoke Tech",
      brand: "Nexus",
      price: 78,
      stock: 55,
      rating: 4.4,
      reviewsCount: 91,
      image: img("photo-1541807084-5c52b6b3adef"),
      description: "Slim rigid sleeve with microfiber lining and magnetic flap.",
    },
    {
      name: "Portable SSD 2TB",
      vendorId: "v_nexus",
      vendorName: "Nexus Tech",
      categoryName: "Bespoke Tech",
      brand: "Nexus",
      price: 219,
      stock: 33,
      rating: 4.9,
      reviewsCount: 402,
      image: img("photo-1597872200969-2b65d56bd16b"),
      description: "USB4 speeds up to 2000MB/s in a pocketable aluminum shell.",
    },
    {
      name: "4K Webcam Studio",
      vendorId: "v_nexus",
      vendorName: "Nexus Tech",
      categoryName: "Bespoke Tech",
      brand: "Nexus",
      price: 149,
      stock: 22,
      rating: 4.3,
      reviewsCount: 167,
      image: img("photo-1587825140708-dfaf72ae4b04"),
      description: "Sony sensor, dual mics, and autofocus tuned for desk lighting.",
    },
    {
      name: "Ergo Split Keyboard",
      vendorId: "v_elementa",
      vendorName: "Elementa",
      categoryName: "Bespoke Tech",
      brand: "Elementa",
      price: 245,
      stock: 14,
      rating: 4.8,
      reviewsCount: 88,
      image: img("photo-1511467687858-23d96c32e4ae"),
      description: "Columnar layout, hot-swap sockets, and tented aluminum case.",
    },
    {
      name: "MagSafe Travel Battery 10K",
      vendorId: "v_nexus",
      vendorName: "Nexus Tech",
      categoryName: "Bespoke Tech",
      brand: "Nexus",
      price: 59,
      stock: 80,
      rating: 4.5,
      reviewsCount: 520,
      image: img("photo-1609091839311-d5365f9ff1c5"),
      description: "Snap-on wireless pack with passthrough charging.",
    },

    // Luxury Goods — Vogue
    {
      name: "Terraform Leather Boots",
      vendorId: "v_vogue",
      vendorName: "Vogue Minimal",
      categoryName: "Luxury Goods",
      brand: "Terraform",
      price: 185,
      stock: 18,
      rating: 4.6,
      reviewsCount: 82,
      image: img("photo-1549298916-b41d501d3772"),
      description: "Full-grain derby boots with Goodyear welt and tonal stitching.",
    },
    {
      name: "Leather Weekend Bag",
      vendorId: "v_vogue",
      vendorName: "Vogue Minimal",
      categoryName: "Luxury Goods",
      brand: "Vogue",
      price: 340,
      stock: 8,
      rating: 4.9,
      reviewsCount: 56,
      image: img("photo-1548036328-c9fa89d128fa"),
      description: "Vegetable-tanned holdall with brass hardware and cotton lining.",
    },
    {
      name: "Slim Cardholder Wallet",
      vendorId: "v_vogue",
      vendorName: "Vogue Minimal",
      categoryName: "Luxury Goods",
      brand: "Vogue",
      price: 68,
      stock: 60,
      rating: 4.7,
      reviewsCount: 203,
      image: img("photo-1627123424574-724758594e93"),
      description: "Six-slot Italian leather cardholder with RFID lining.",
    },
    {
      name: "Brushed Steel Chronograph",
      vendorId: "v_vogue",
      vendorName: "Vogue Minimal",
      categoryName: "Luxury Goods",
      brand: "Aurum",
      price: 520,
      stock: 9,
      rating: 4.8,
      reviewsCount: 74,
      image: img("photo-1524592094714-0f0654e20314"),
      description: "40mm automatic chronograph with sapphire crystal and 100m WR.",
    },
    {
      name: "Silk Pocket Square Set",
      vendorId: "v_vogue",
      vendorName: "Vogue Minimal",
      categoryName: "Luxury Goods",
      brand: "Vogue",
      price: 48,
      stock: 35,
      rating: 4.4,
      reviewsCount: 41,
      image: img("photo-1594938298603-c8148c4dae35"),
      description: "Hand-rolled silk squares in three seasonal colorways.",
    },
    {
      name: "Cashmere Scarf — Charcoal",
      vendorId: "v_vogue",
      vendorName: "Vogue Minimal",
      categoryName: "Luxury Goods",
      brand: "Vogue",
      price: 165,
      stock: 20,
      rating: 4.9,
      reviewsCount: 119,
      image: img("photo-1520903920243-00d872a2d1c9"),
      description: "Pure Mongolian cashmere, 180×30cm, finished with hand-fringe.",
    },
    {
      name: "Minimal Gold Hoops",
      vendorId: "v_vogue",
      vendorName: "Vogue Minimal",
      categoryName: "Luxury Goods",
      brand: "Aurum",
      price: 128,
      stock: 27,
      rating: 4.6,
      reviewsCount: 95,
      image: img("photo-1535632066927-ab7c9ab60908"),
      description: "14k gold-filled hoops with hinged clasp — lightweight everyday wear.",
    },

    // Wellness — Aurum
    {
      name: "Velocity Run '24 Red",
      vendorId: "v_aurum",
      vendorName: "Aurum Collective",
      categoryName: "Wellness & Ritual",
      brand: "Velocity",
      price: 120,
      stock: 5,
      rating: 4.9,
      reviewsCount: 512,
      image: img("photo-1542291026-7eec264c27ff"),
      description: "Responsive foam midsole and breathable knit upper for daily miles.",
    },
    {
      name: "Yoga Mat Pro Cork",
      vendorId: "v_aurum",
      vendorName: "Aurum Collective",
      categoryName: "Wellness & Ritual",
      brand: "Aurum",
      price: 72,
      stock: 45,
      rating: 4.7,
      reviewsCount: 288,
      image: img("photo-1601925260368-ae2f83cf8b7f"),
      description: "Natural cork surface with natural rubber base — non-slip when wet.",
    },
    {
      name: "Adjustable Dumbbells 24kg",
      vendorId: "v_aurum",
      vendorName: "Aurum Collective",
      categoryName: "Wellness & Ritual",
      brand: "Velocity",
      price: 289,
      stock: 11,
      rating: 4.8,
      reviewsCount: 176,
      image: img("photo-1517836357463-d25dfeac3438"),
      description: "Space-saving pair with secure dial adjustment from 2–24kg each.",
    },
    {
      name: "Recovery Foam Roller",
      vendorId: "v_aurum",
      vendorName: "Aurum Collective",
      categoryName: "Wellness & Ritual",
      brand: "Aurum",
      price: 34,
      stock: 70,
      rating: 4.5,
      reviewsCount: 340,
      image: img("photo-1571019614242-c5c5dee9f50b"),
      description: "High-density EVA with textured grip zones for deep tissue work.",
    },
    {
      name: "Ceramic Matcha Bowl Set",
      vendorId: "v_aurum",
      vendorName: "Aurum Collective",
      categoryName: "Wellness & Ritual",
      brand: "Aurum",
      price: 58,
      stock: 28,
      rating: 4.6,
      reviewsCount: 63,
      image: img("photo-1564890369478-c89ca6d9cde9"),
      description: "Hand-glazed chawan with bamboo whisk and scoop.",
    },
    {
      name: "Weighted Jump Rope",
      vendorId: "v_aurum",
      vendorName: "Aurum Collective",
      categoryName: "Wellness & Ritual",
      brand: "Velocity",
      price: 29,
      stock: 90,
      rating: 4.4,
      reviewsCount: 210,
      image: img("photo-1518611012118-696072aa579a"),
      description: "Ball-bearing handles and interchangeable weighted cable.",
    },
    {
      name: "Sleep Mask Silk",
      vendorId: "v_aurum",
      vendorName: "Aurum Collective",
      categoryName: "Wellness & Ritual",
      brand: "Aurum",
      price: 36,
      stock: 50,
      rating: 4.7,
      reviewsCount: 154,
      image: img("photo-1540555700478-4be289fbecef"),
      description: "Mulberry silk sleep mask with adjustable strap and contoured fit.",
    },

    // Home Studio — Elementa
    {
      name: "Minimalist Desk Lamp",
      vendorId: "v_elementa",
      vendorName: "Elementa",
      categoryName: "Home Studio",
      brand: "Elementa",
      price: 89,
      stock: 42,
      rating: 4.5,
      reviewsCount: 67,
      image: img("photo-1507473885765-e6ed057f782c"),
      description: "Warm-dim LED task lamp with brass arm and matte base.",
    },
    {
      name: "Oak Standing Desk 140cm",
      vendorId: "v_elementa",
      vendorName: "Elementa",
      categoryName: "Home Studio",
      brand: "Elementa",
      price: 699,
      stock: 7,
      rating: 4.8,
      reviewsCount: 92,
      image: img("photo-1518455027359-f3f8164ba6bd"),
      description: "Solid oak top on dual-motor frame with memory presets.",
    },
    {
      name: "Linen Desk Mat",
      vendorId: "v_elementa",
      vendorName: "Elementa",
      categoryName: "Home Studio",
      brand: "Elementa",
      price: 42,
      stock: 65,
      rating: 4.3,
      reviewsCount: 118,
      image: img("photo-1586023492125-27b2c045efd7"),
      description: "Stitched linen desk mat in natural flax — 80×40cm.",
    },
    {
      name: "Ceramic Planter Medium",
      vendorId: "v_elementa",
      vendorName: "Elementa",
      categoryName: "Home Studio",
      brand: "Elementa",
      price: 38,
      stock: 48,
      rating: 4.6,
      reviewsCount: 77,
      image: img("photo-1485955900006-10f4d324d411"),
      description: "Stoneware planter with drainage saucer in matte bone.",
    },
    {
      name: "Acoustic Wall Panel Pair",
      vendorId: "v_elementa",
      vendorName: "Elementa",
      categoryName: "Home Studio",
      brand: "Elementa",
      price: 156,
      stock: 16,
      rating: 4.5,
      reviewsCount: 54,
      image: img("photo-1618221195710-dd6b41faaea6"),
      description: "Fabric-wrapped acoustic panels for home studios — set of two.",
    },
    {
      name: "Modular Shelf Unit",
      vendorId: "v_elementa",
      vendorName: "Elementa",
      categoryName: "Home Studio",
      brand: "Elementa",
      price: 320,
      stock: 10,
      rating: 4.7,
      reviewsCount: 61,
      image: img("photo-1594026112284-02bb6f3352fe"),
      description: "Powder-coated steel frame with solid wood shelves.",
    },
    {
      name: "Scented Candle Cedar",
      vendorId: "v_elementa",
      vendorName: "Elementa",
      categoryName: "Home Studio",
      brand: "Elementa",
      price: 32,
      stock: 100,
      rating: 4.8,
      reviewsCount: 430,
      image: img("photo-1602604386676-46c0c0f5e0f0"),
      description: "Soy wax candle with cedar, vetiver, and smoke notes — 50hr burn.",
    },

    // Fashion — Atelier Nord
    {
      name: "Wool Overcoat Camel",
      vendorId: "v_atelier",
      vendorName: "Atelier Nord",
      categoryName: "Fashion",
      brand: "Nord",
      price: 420,
      stock: 12,
      rating: 4.9,
      reviewsCount: 88,
      image: img("photo-1539533018447-63fcce2678e3"),
      description: "Double-faced wool coat with notch lapel and hidden placket.",
    },
    {
      name: "Organic Cotton Tee Pack",
      vendorId: "v_atelier",
      vendorName: "Atelier Nord",
      categoryName: "Fashion",
      brand: "Nord",
      price: 54,
      stock: 120,
      rating: 4.5,
      reviewsCount: 640,
      image: img("photo-1521572163474-6864f9cf17ab"),
      description: "Three-pack heavyweight tees in bone, ink, and slate.",
    },
    {
      name: "Selvedge Denim Jean",
      vendorId: "v_atelier",
      vendorName: "Atelier Nord",
      categoryName: "Fashion",
      brand: "Nord",
      price: 168,
      stock: 24,
      rating: 4.7,
      reviewsCount: 211,
      image: img("photo-1542272604-787c3835535d"),
      description: "14oz Japanese selvedge, tapered fit, raw indigo.",
    },
    {
      name: "Linen Summer Shirt",
      vendorId: "v_atelier",
      vendorName: "Atelier Nord",
      categoryName: "Fashion",
      brand: "Nord",
      price: 98,
      stock: 36,
      rating: 4.6,
      reviewsCount: 143,
      image: img("photo-1596755094514-f87e34085b2c"),
      description: "Relaxed camp collar shirt in European linen.",
    },
    {
      name: "Merino Crew Sweater",
      vendorId: "v_atelier",
      vendorName: "Atelier Nord",
      categoryName: "Fashion",
      brand: "Nord",
      price: 145,
      stock: 19,
      rating: 4.8,
      reviewsCount: 176,
      image: img("photo-1576566588028-4147f3842f27"),
      description: "Fine-gauge merino crew with ribbed cuffs and hem.",
    },
    {
      name: "Trail Runner Low",
      vendorId: "v_atelier",
      vendorName: "Atelier Nord",
      categoryName: "Fashion",
      brand: "Velocity",
      price: 138,
      stock: 30,
      rating: 4.5,
      reviewsCount: 290,
      image: img("photo-1606107557195-0e29a4b5b4aa"),
      description: "Hybrid lifestyle runner with Vibram outsole and suede overlays.",
    },
    {
      name: "Structured Tote Canvas",
      vendorId: "v_atelier",
      vendorName: "Atelier Nord",
      categoryName: "Fashion",
      brand: "Nord",
      price: 110,
      stock: 22,
      rating: 4.4,
      reviewsCount: 99,
      image: img("photo-1590874103328-eac38a683ce7"),
      description: "Waxed canvas tote with leather handles and laptop sleeve.",
    },

    // Kitchen — Hearth & Copper
    {
      name: "Cast Iron Skillet 28cm",
      vendorId: "v_hearth",
      vendorName: "Hearth & Copper",
      categoryName: "Kitchen",
      brand: "Hearth",
      price: 85,
      stock: 40,
      rating: 4.9,
      reviewsCount: 780,
      image: img("photo-1556910103-1c02745aae4d"),
      description: "Pre-seasoned skillet with helper handle and pour spouts.",
    },
    {
      name: "Chef Knife 8\" Damascus",
      vendorId: "v_hearth",
      vendorName: "Hearth & Copper",
      categoryName: "Kitchen",
      brand: "Copper",
      price: 189,
      stock: 15,
      rating: 4.8,
      reviewsCount: 215,
      image: img("photo-1593618998160-e34014e67546"),
      description: "67-layer damascus steel with pakkawood handle.",
    },
    {
      name: "Pour-Over Coffee Set",
      vendorId: "v_hearth",
      vendorName: "Hearth & Copper",
      categoryName: "Kitchen",
      brand: "Hearth",
      price: 64,
      stock: 38,
      rating: 4.7,
      reviewsCount: 332,
      image: img("photo-1495474472287-4d71bcdd2085"),
      description: "Ceramic dripper, server, and filters — for 1–4 cups.",
    },
    {
      name: "Stoneware Dinner Set (4)",
      vendorId: "v_hearth",
      vendorName: "Hearth & Copper",
      categoryName: "Kitchen",
      brand: "Hearth",
      price: 128,
      stock: 20,
      rating: 4.6,
      reviewsCount: 148,
      image: img("photo-1578749556568-bc2c40e68b61"),
      description: "Reactive glaze plates and bowls for four — dishwasher safe.",
    },
    {
      name: "Copper Cocktail Shaker",
      vendorId: "v_hearth",
      vendorName: "Hearth & Copper",
      categoryName: "Kitchen",
      brand: "Copper",
      price: 52,
      stock: 44,
      rating: 4.5,
      reviewsCount: 87,
      image: img("photo-1514362545857-3bc16c4c7d1b"),
      description: "Weighted copper-plated shaker with integrated strainer.",
    },
    {
      name: "Olive Wood Cutting Board",
      vendorId: "v_hearth",
      vendorName: "Hearth & Copper",
      categoryName: "Kitchen",
      brand: "Hearth",
      price: 76,
      stock: 26,
      rating: 4.8,
      reviewsCount: 164,
      image: img("photo-1600565193348-f74bd3c7ccdf"),
      description: "End-grain olive wood board with juice groove.",
    },
    {
      name: "Espresso Tamper 58mm",
      vendorId: "v_hearth",
      vendorName: "Hearth & Copper",
      categoryName: "Kitchen",
      brand: "Copper",
      price: 45,
      stock: 33,
      rating: 4.7,
      reviewsCount: 102,
      image: img("photo-1511920170033-f8396924c348"),
      description: "Calibrated spring tamper for consistent 30lb pressure.",
    },

    // Outdoor
    {
      name: "Ultralight Daypack 20L",
      vendorId: "v_atelier",
      vendorName: "Atelier Nord",
      categoryName: "Outdoor",
      brand: "Nord",
      price: 118,
      stock: 31,
      rating: 4.6,
      reviewsCount: 201,
      image: img("photo-1553062407-98eeb64c6a62"),
      description: "Ripstop nylon pack with ventilated back panel and hip belt.",
    },
    {
      name: "Insulated Water Bottle 750ml",
      vendorId: "v_aurum",
      vendorName: "Aurum Collective",
      categoryName: "Outdoor",
      brand: "Velocity",
      price: 36,
      stock: 95,
      rating: 4.7,
      reviewsCount: 890,
      image: img("photo-1602143407151-7111542de6e8"),
      description: "Double-wall stainless, 24h cold / 12h hot, leak-proof lid.",
    },
    {
      name: "Travel Packing Cubes (3)",
      vendorId: "v_nexus",
      vendorName: "Nexus Tech",
      categoryName: "Outdoor",
      brand: "Nexus",
      price: 39,
      stock: 70,
      rating: 4.5,
      reviewsCount: 455,
      image: img("photo-1565026057447-bc90a3dceb87"),
      description: "Compression packing cubes in three sizes — recycled ripstop.",
    },
    {
      name: "Compact Camping Lantern",
      vendorId: "v_elementa",
      vendorName: "Elementa",
      categoryName: "Outdoor",
      brand: "Elementa",
      price: 48,
      stock: 40,
      rating: 4.4,
      reviewsCount: 133,
      image: img("photo-1504280390367-361c6d9f38f4"),
      description: "USB-C rechargeable lantern with warm/cool modes and power bank.",
    },
    {
      name: "Polarized Trail Sunglasses",
      vendorId: "v_atelier",
      vendorName: "Atelier Nord",
      categoryName: "Outdoor",
      brand: "Nord",
      price: 92,
      stock: 28,
      rating: 4.6,
      reviewsCount: 187,
      image: img("photo-1511499767150-a48a237f0083"),
      description: "Lightweight acetate frames with polarized mineral lenses.",
    },

    // Beauty
    {
      name: "Vitamin C Serum 30ml",
      vendorId: "v_aurum",
      vendorName: "Aurum Collective",
      categoryName: "Beauty",
      brand: "Aurum",
      price: 48,
      stock: 55,
      rating: 4.7,
      reviewsCount: 620,
      image: img("photo-1620916562284-50c901726c10"),
      description: "15% L-ascorbic acid with ferulic acid and vitamin E.",
    },
    {
      name: "Clay Face Mask Jar",
      vendorId: "v_aurum",
      vendorName: "Aurum Collective",
      categoryName: "Beauty",
      brand: "Aurum",
      price: 28,
      stock: 62,
      rating: 4.5,
      reviewsCount: 278,
      image: img("photo-1556228578-0d85b1a4d571"),
      description: "Kaolin and French green clay for weekly deep cleanse.",
    },
    {
      name: "Cedarwood Eau de Parfum",
      vendorId: "v_vogue",
      vendorName: "Vogue Minimal",
      categoryName: "Beauty",
      brand: "Vogue",
      price: 98,
      stock: 18,
      rating: 4.8,
      reviewsCount: 141,
      image: img("photo-1541643600914-78b084683601"),
      description: "Woody aromatic with cedar, bergamot, and soft musk — 50ml.",
    },
    {
      name: "Beard Grooming Kit",
      vendorId: "v_hearth",
      vendorName: "Hearth & Copper",
      categoryName: "Beauty",
      brand: "Hearth",
      price: 44,
      stock: 35,
      rating: 4.6,
      reviewsCount: 198,
      image: img("photo-1621607512214-68297480165e"),
      description: "Oil, balm, and boar brush in a travel tin.",
    },
    {
      name: "Ceramic Diffuser Stone",
      vendorId: "v_elementa",
      vendorName: "Elementa",
      categoryName: "Beauty",
      brand: "Elementa",
      price: 26,
      stock: 48,
      rating: 4.3,
      reviewsCount: 72,
      image: img("photo-1608571423902-eed4a5ad8108"),
      description: "Porous ceramic disc for essential oils — desk or shelf.",
    },
    {
      name: "SPF 50 Mineral Stick",
      vendorId: "v_aurum",
      vendorName: "Aurum Collective",
      categoryName: "Beauty",
      brand: "Aurum",
      price: 22,
      stock: 80,
      rating: 4.5,
      reviewsCount: 360,
      image: img("photo-1556228720-195a672e8a03"),
      description: "Zinc oxide stick for face and lips — reef-conscious formula.",
    },

    // More variety / price range
    {
      name: "Bluetooth Speaker Mini",
      vendorId: "v_nexus",
      vendorName: "Nexus Tech",
      categoryName: "Bespoke Tech",
      brand: "Nexus",
      price: 79,
      stock: 50,
      rating: 4.4,
      reviewsCount: 505,
      image: img("photo-1608043152269-423dbba4e7e1"),
      description: "Pocket speaker with punchy bass and 12-hour playtime.",
    },
    {
      name: "Noise-Isolating Office Chair Mat",
      vendorId: "v_elementa",
      vendorName: "Elementa",
      categoryName: "Home Studio",
      brand: "Elementa",
      price: 95,
      stock: 17,
      rating: 4.2,
      reviewsCount: 44,
      image: img("photo-1497366216548-37526070297c"),
      description: "Felt chair mat that protects floors and softens roll noise.",
    },
    {
      name: "Limited Edition Runner Black",
      vendorId: "v_aurum",
      vendorName: "Aurum Collective",
      categoryName: "Wellness & Ritual",
      brand: "Velocity",
      price: 160,
      stock: 0,
      rating: 4.9,
      reviewsCount: 88,
      image: img("photo-1460353581641-37baddab0fa2"),
      description: "Sold-out colorway — waitlist restock pending.",
    },
    {
      name: "Hand-Thrown Mug Pair",
      vendorId: "v_hearth",
      vendorName: "Hearth & Copper",
      categoryName: "Kitchen",
      brand: "Hearth",
      price: 42,
      stock: 3,
      rating: 4.8,
      reviewsCount: 112,
      image: img("photo-1514228742587-6b1558fcca3d"),
      description: "Speckled stoneware mugs — each unique. Low stock.",
    },
    {
      name: "Linen Throw Blanket",
      vendorId: "v_atelier",
      vendorName: "Atelier Nord",
      categoryName: "Home Studio",
      brand: "Nord",
      price: 135,
      stock: 21,
      rating: 4.7,
      reviewsCount: 156,
      image: img("photo-1584100936595-c0654b55a2e2"),
      description: "Stonewashed European linen throw — softens with every wash.",
    },
    {
      name: "Smart LED Strip Kit 5m",
      vendorId: "v_nexus",
      vendorName: "Nexus Tech",
      categoryName: "Bespoke Tech",
      brand: "Nexus",
      price: 49,
      stock: 60,
      rating: 4.3,
      reviewsCount: 710,
      image: img("photo-1558002038-1055907df827"),
      description: "RGBWW strip with app control, scenes, and music sync.",
    },
  ];

  let created = 0;
  let updated = 0;

  for (const p of prods) {
    const categoryId = catMap[p.categoryName];
    if (!categoryId) {
      console.warn(`  Missing category for ${p.name}`);
      continue;
    }

    const data = {
      name: p.name,
      vendorId: p.vendorId,
      vendorName: p.vendorName,
      categoryId,
      categoryName: p.categoryName,
      brand: p.brand,
      price: p.price,
      stock: p.stock,
      rating: p.rating,
      reviewsCount: p.reviewsCount,
      image: p.image,
      images: p.images?.length ? p.images : [p.image],
      description: p.description,
      isActive: true,
    };

    const ex = await prisma.product.findFirst({ where: { name: p.name } });
    if (!ex) {
      await prisma.product.create({ data });
      created += 1;
      console.log(`  + ${p.name}`);
    } else {
      await prisma.product.update({
        where: { id: ex.id },
        data: {
          image: data.image,
          images: data.images,
          description: data.description,
          price: data.price,
          stock: data.stock,
          rating: data.rating,
          reviewsCount: data.reviewsCount,
          brand: data.brand,
          vendorId: data.vendorId,
          vendorName: data.vendorName,
          categoryId: data.categoryId,
          categoryName: data.categoryName,
          isActive: true,
        },
      });
      updated += 1;
      console.log(`  ~ ${p.name}`);
    }
  }

  const total = await prisma.product.count();
  console.log(`\nSeed complete — created ${created}, updated ${updated}, total products ${total}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
