services:
  - type: web
    name: vendex-api
    runtime: node
    rootDir: backend
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_qnQ8xY2MbjiA@ep-proud-cake-avvz8kaa-pooler.c-11.us-east-1.aws.neon.tech/neondb?channel_binding=require&sslmode=require"
      - key: DATABASE_URL_UNPOOLED
        value: "postgresql://neondb_owner:npg_qnQ8xY2MbjiA@ep-proud-cake-avvz8kaa.c-11.us-east-1.aws.neon.tech/neondb?sslmode=require"
      - key: JWT_SECRET
        value: "vendex_super_secret_jwt_key_2026"
      - key: PORT
        value: "3001"
      - key: NODE_VERSION
        value: "20.18.0"
