/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Brand
        primary: "#97001b",
        "primary-container": "#c0152a",
        "primary-fixed": "#ffdad8",
        "primary-fixed-dim": "#ffb3b0",
        "on-primary": "#ffffff",
        "on-primary-container": "#ffd2d0",
        "on-primary-fixed": "#410006",
        "on-primary-fixed-variant": "#93001a",
        "inverse-primary": "#ffb3b0",

        // Secondary
        secondary: "#5f5e5e",
        "secondary-container": "#e2dfde",
        "secondary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#c8c6c5",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#636262",
        "on-secondary-fixed": "#1c1b1b",
        "on-secondary-fixed-variant": "#474746",

        // Tertiary
        tertiary: "#484946",
        "tertiary-container": "#60615d",
        "tertiary-fixed": "#e3e3de",
        "tertiary-fixed-dim": "#c6c7c2",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#dcdcd8",
        "on-tertiary-fixed": "#1a1c19",
        "on-tertiary-fixed-variant": "#464744",

        // Error
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",

        // Surface
        background: "#fafaf5",
        "on-background": "#1a1c19",
        surface: "#fafaf5",
        "surface-dim": "#dadad5",
        "surface-bright": "#fafaf5",
        "surface-variant": "#e3e3de",
        "surface-tint": "#bc1128",
        "surface-container": "#eeeee9",
        "surface-container-low": "#f4f4ef",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e8e8e3",
        "surface-container-highest": "#e3e3de",
        "on-surface": "#1a1c19",
        "on-surface-variant": "#5b403e",
        "inverse-surface": "#2f312e",
        "inverse-on-surface": "#f1f1ec",

        // Outline
        outline: "#906f6d",
        "outline-variant": "#e4bdbb",

        // Semantic status
        success: "#2d7a4f",
        "success-container": "#e6f4ea",
        "on-success-container": "#1e4620",
        warning: "#b45309",
        "warning-container": "#fef3c7",
        "on-warning-container": "#78350f",
        info: "#1e40af",
        "info-container": "#dbeafe",
        "on-info-container": "#1e3a5f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        md: "24px",
        base: "4px",
        gutter: "24px",
        xl: "64px",
        xs: "8px",
        "container-max": "1280px",
        sm: "16px",
        lg: "40px",
        header: "72px",
        "bottom-nav": "72px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ['"IBM Plex Mono"', "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        meta: ['"IBM Plex Mono"', "ui-monospace", "monospace"],
        "label-sm": ['"IBM Plex Mono"', "ui-monospace", "monospace"],
        "label-md": ["Inter"],
        "display-lg": ["Inter"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        meta: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
