/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#1c1b1b",
        "on-secondary-container": "#636262",
        "on-primary-fixed": "#410006",
        "primary-fixed": "#ffdad8",
        "inverse-on-surface": "#f1f1ec",
        "error": "#ba1a1a",
        "outline-variant": "#e4bdbb",
        "on-surface-variant": "#5b403e",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#c6c7c2",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#e5e2e1",
        "surface-container": "#eeeee9",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#ffb3b0",
        "surface-container-low": "#f4f4ef",
        "secondary": "#5f5e5e",
        "on-primary-container": "#ffd2d0",
        "inverse-primary": "#ffb3b0",
        "tertiary": "#484946",
        "on-secondary": "#ffffff",
        "surface-bright": "#fafaf5",
        "on-tertiary-fixed": "#1a1c19",
        "surface-dim": "#dadad5",
        "tertiary-container": "#60615d",
        "on-secondary-fixed-variant": "#474746",
        "secondary-container": "#e2dfde",
        "outline": "#906f6d",
        "on-background": "#1a1c19",
        "primary-container": "#c0152a",
        "surface": "#fafaf5",
        "inverse-surface": "#2f312e",
        "on-primary-fixed-variant": "#93001a",
        "on-tertiary-fixed-variant": "#464744",
        "surface-container-highest": "#e3e3de",
        "on-error-container": "#93000a",
        "on-surface": "#1a1c19",
        "on-tertiary-container": "#dcdcd8",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "surface-container-high": "#e8e8e3",
        "tertiary-fixed": "#e3e3de",
        "background": "#fafaf5",
        "surface-variant": "#e3e3de",
        "surface-tint": "#bc1128",
        "secondary-fixed-dim": "#c8c6c5",
        "primary": "#97001b"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "md": "24px",
        "base": "4px",
        "gutter": "24px",
        "xl": "64px",
        "xs": "8px",
        "container-max": "1280px",
        "sm": "16px",
        "lg": "40px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "meta": ["Inter"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "display-lg": ["Inter"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "meta": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
